### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vanjusa** [ngimb64/Advanced-Keylogger#4]
Please, can you tell me what is the solution for this problem?
![Capture 1](https://user-images.githubusercontent.com/115928455/201694102-d4ad5c03-46e3-4591-a833-0af69ed14804.PNG)

**Comment by ngimb64** [comment]
Hello vanjusa! I personally have never encountered this error myself, but it has to do with the validation of a SSL/TLS certificate associated with python when a request is made to gather pip, setuptools, etc. This link https://www.howtouselinux.com/post/ssl-certificate_verify_failed-in-python provides a few options, one being more ideal as the others require editing code to disable SSL verification. To fix the error it would be ideal to update the SSL certificates associated for python with pip. You could also try a system trust store to avoid pip missing custom certificate chains (https://pip.pypa.io/en/stable/topics/https-certificates/). What version of Python are you using?

**Comment by vanjusa** [comment]
Hello Nicholas! Thank you for fast reply! Version of Python that I using is 3.8.10 (32-bit), Win 7-64bit......
![Capture 2](https://user-images.githubusercontent.com/115928455/201738888-6fb071a0-1c23-49e0-9855-ea83a26bb992.PNG)

**Comment by vanjusa** [comment]
![Capture 3](https://user-images.githubusercontent.com/115928455/201748652-2d5768cc-7ecf-47f7-ae66-2a0817494e3b.PNG)
![Capture 4](https://user-images.githubusercontent.com/115928455/201748663-f0e29414-5e34-44d1-bb2a-2e4f82ea3829.PNG)

**Comment by vanjusa** [comment]
I have upgraded setuptools from 56.0.0 to 65.5.1 and nothing has change.
![Capture 6](https://user-images.githubusercontent.com/115928455/201763160-cc36d946-ea5f-4cb6-9856-5a6650e1e459.PNG)

**Comment by ngimb64** [comment]
Did you try "pip install --upgrade certifi" in the command prompt? Though I do not think it would I have to do with this issue, I would also recommend using a 64 bit version if your system is 64 bit.

**Comment by ngimb64** [comment]
If the problem persists there is a simple alternative. Create a venv with python -m venv [venv name], activate the environment, then simply do pip -r packages.txt to install the packages into the virtual environment. Thats essentially what the script does, but it works differently  when doing a custom script vs through the module. I would still recommend upgrading certifi because it seems your SSL certificates are out of date, which could have do with Windows 7 being an older OS. I ran the script myself earlier, but it was on Windows 10.

**Comment by ngimb64** [comment]
My bad I missed some of the details in the screenshot before and it looks like most of the packages installed. After running the script on the package list showed that some of the packages are out of date, switch the scipy version to 1.9.3 and pywin32 to 305 in the windows_packages.txt and see if it works. I plan on doing some maintainence updates on my repos soon, which I make sure all the packages are updated. If for some reson your still getting certificate errors, I would suggests getting a fresh copy of 64 bit Python and sticking to the default installation and it should work with the updated packages.

**Comment by ngimb64** [comment]
Also Pillow needs to be 9.3.0 my bad. If those three packages are updated the installation will be successful:

Pillow==9.3.0
scipy==1.9.3
pywin32==305

**Comment by vanjusa** [comment]
After this action,

"If the problem persists there is a simple alternative. Create a venv with python -m venv [venv name], activate the environment, then simply do pip -r packages.txt to install the packages into the virtual environment. Thats essentially what the script does, but it works differently when doing a custom script vs through the module"

this happened :-)



![Capture 7](https://user-images.githubusercontent.com/115928455/201780938-0c763f03-2446-4081-b955-56d578e08090.PNG)
![Capture 8](https://user-images.githubusercontent.com/115928455/201780948-44c8862a-11bb-4198-b9ca-5fecb25b9e27.PNG)

**Comment by ngimb64** [comment]
Ok this is good news, the error in thread 3 should be fixed by updating the for loop at line 221 with the attached screenshot. I'm almost certain the other error associated with the mic recording has to do with the channel the mic is on, which depends on the OS but I was unable to figure out how to query the channel at the time and just started at 0 and incremented per attempt until it worked.
![Fix1](https://user-images.githubusercontent.com/56981761/201784157-45b8b8ea-d1e9-4057-9c3d-516193bb8c68.png)

**Comment by vanjusa** [comment]
> Also Pillow needs to be 9.3.0 my bad. If those three packages are updated the installation will be successful:
> 
> Pillow==9.3.0 scipy==1.9.3 pywin32==305

After this upgrade all ended with a complete mess.

![Capture 9](https://user-images.githubusercontent.com/115928455/201784090-e9e14f4f-d469-4061-a650-b942ddc14ed0.PNG)

![Capture 10](https://user-images.githubusercontent.com/115928455/201784100-b024f22c-8cb0-4ecf-a4d8-1dab59e48be3.PNG)

**Comment by ngimb64** [comment]
Your pip is not even up to date, thats why

**Comment by ngimb64** [comment]
It can only install packages were available at that time, its pip install --upgrade pip to update pip

**Comment by vanjusa** [comment]
> It can only install packages were available at that time, its pip install --upgrade pip to update pip

![Capture 11](https://user-images.githubusercontent.com/115928455/201787299-529fb964-1133-4544-8d83-a264ff61b23b.PNG)
![Capture 12](https://user-images.githubusercontent.com/115928455/201787309-54148dcd-0e66-42b2-b7ec-22d42237a3af.PNG)


![Capture 10](https://user-images.githubusercontent.com/115928455/201787357-a91b971c-b08a-40d6-ae53-5154e39d21f8.PNG)

![Capture 13](https://user-images.githubusercontent.com/115928455/201787372-9fdea873-607f-464c-babf-0a4510dd38a0.PNG)

**Comment by vanjusa** [comment]
What do you think if I uninstall Python 32-bit and install the 64-bit version of it?

**Comment by ngimb64** [comment]
Your trying to upgrade the system pip instead of the virtual environment which does not seem to be activated at all, Python avoids installing system packages to avoid various issues. So even when your checking the version your not even looking at the right. It even says on the output that the version of pip needs to be upgraded.

**Comment by ngimb64** [comment]
Yes I would get a recent version and 64bit if that is your system.

**Comment by vanjusa** [comment]
> Yes I would get a recent version and 64bit if that is your system.

Ok, thanks a lot, I will do that.

**Comment by ngimb64** [comment]
remember when your in a virtual environment, when you execute a command it could very well still be based on the system path. Meaning when you go to update pip it might use the system version of Python instead. The best way to avoid such issues would be to specify an absolute path to the pip in the venv folder or just go in the venv folder with pip and execute upgrades locally from there

**Comment by vanjusa** [comment]
Ouuu, I don't now about that...thanks...
I have information that Python ver. >3.8.10. can't be
 installed on win 7.
Is that right?

**Comment by ngimb64** [comment]
Not too sure because I don't use Windows 7, but It seems as long as your below verson 3.9 it should be fine
